### ISSUE TITLE
no ltp display 

### ISSUE THREAD

**Issue by rajesh98p** [sathyarajshetigar/Shoonya-Scalper#4]
i downloaded the version 1.4 .
when i open login successful but there is no price and index ltp showing .
i have latest windows 11 64 b with pyv 3.11 install

**Comment by sathyarajshetigar** [comment]
Try in on weekdays and revert back if you are facing the issue.

**Comment by rajesh98p** [comment]
> Try in on weekdays and revert back if you are facing the issue.

here is the error going on 
[2023-06-12.log](https://github.com/sathyarajshetigar/Shoonya-Scalper/files/11717361/2023-06-12.log)

**Comment by sathyarajshetigar** [comment]
@rajesh98p Please run the same again in a few trading sessions. let me know if the issue persists. Also, Try disabling firewall for the scalper or try running it as Admin and check if it makes any difference.

**Comment by sathyarajshetigar** [comment]
https://t.me/sathyarajshettigar for quick support
