### ISSUE TITLE
kindly add finnifty also please 

### ISSUE THREAD

**Issue by rajesh98p** [sathyarajshetigar/Shoonya-Scalper#5]

**Comment by rajesh98p** [comment]
good after noon  please add fin nifty also for treading

**Comment by sathyarajshetigar** [comment]
Its already present
![image](https://github.com/sathyarajshetigar/Shoonya-Scalper/assets/42057975/a19db5ba-3e73-4d1c-8083-a9ae2406b62a)

**Comment by rajesh98p** [comment]
YES its present but not working ...mean not showing ltp or changing anything ,may be only nifty and banknifty active only

**Comment by sathyarajshetigar** [comment]
Try deleting the content of last_download_date.txt and check, Let me know if the issue persists.

**Comment by sathyarajshetigar** [comment]
https://t.me/sathyarajshettigar for quick support
