### ISSUE TITLE
WebSocket error_callback Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by MrVizier** [sathyarajshetigar/Shoonya-Scalper#6]
WebSocket error_callback Unknown format code 'f' for object of type 'str'

**Comment by sathyarajshetigar** [comment]
Delete these files and run the app again
![image](https://github.com/sathyarajshetigar/Shoonya-Scalper/assets/42057975/be0b70bf-5cb3-4055-af10-51594ebe0649)

**Comment by MrVizier** [comment]
Thank you.

**Comment by sathyarajshetigar** [comment]
Did it solve the issue?

**Comment by MrVizier** [comment]
yes, it did solve the issue.
