### ISSUE TITLE
One of the items in the 'lots' list is not a valid number.

### ISSUE THREAD

**Issue by MrVizier** [sathyarajshetigar/Shoonya-Scalper#7]
entrybuffer: '0'
lockprofitafter: '20'
lockprofitat: '10'
lots: 1, 2,
ordertype: M
pricetype: LMT
sl: '10'
slbuffer: '0'
tar: '0'
tsl: '10'

my setting.yml

**Comment by sathyarajshetigar** [comment]
bankNiftyLots: '15'
candleinterval: '5'
entrybuffer: '0'
lockprofitafter: '20'
lockprofitat: '5'
niftyLots: '10'
ordertype: I
pricetype: MKT
sl: '20'
slbuffer: '0'
strikes:
- -4
- -3
- -2
- -1
- 0
- 1
- 2
- 3
- 4
tar: '40'
tsl: '20'

This is how it should look. did you delete strikes?
your lots: 1, 2, it should be lots: 1 or any integer number

**Comment by MrVizier** [comment]
Your solution worked perfectly and I was able to continue with my task. You have been very helpful and courteous throughout this process.
